/*
 * Copyright (C) by Argonne National Laboratory
 *     See COPYRIGHT in top-level directory
 */

#include <mpi.h>

/* Simple function added as a sample.  This file needs to be almost
 * entirely autogenerated. */

int MPI_Init(int *argc, char ***argv)
{
    int ret = PMPI_Init(argc, argv);

    return ret;
}
